### ISSUE TITLE
Automatically add <p></p> in new defined tag

### ISSUE THREAD

**Issue by hugohuynh** [jsdoc3/jsdoc3.github.com#139] opened 2016-10-06 02:24 UTC
Hi,
I implemented a plugin so call route.js to define new tag so called "route". Code in the file route.js

```
exports.defineTags = function(dictionary) {
  dictionary.defineTag('api', {
    onTagged: handleRouteTag
};

function handleRouteTag(doclet, tag) {
  if(tag.value) doclet.api = tag.value;
}
```

The I tried to check doclet and saw that route tag is always automatically added paragraph in doclet. Then I tried another name api `doclet.api = tag.value;` result also the same. If I change to a name differ from `route` and  `api` for example `newName` will be ok. Please view attached image below.

![jdoc](https://cloud.githubusercontent.com/assets/2569420/19138704/3692324e-8bb1-11e6-868f-02b4bd1c3672.png)

Please advice,
Thanks,
Trung.

**Comment by hegemonic** [comment] 2017-07-07 06:09
Duplicate of jsdoc3/jsdoc#1274.

**Closed by hegemonic** 2017-07-07 06:09 UTC
